---
- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: create directory
  ansible.builtin.file:
    path: /home/ubuntu/alertmanager
    state: directory

- name: download alertmanager tarball
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz"
    dest: "/home/ubuntu/alertmanager/alertmanager-0.26.0.linux-amd64.tar.gz"

- name: unpack installation files
  ansible.builtin.unarchive:
    src: "/home/ubuntu/alertmanager/alertmanager-0.26.0.linux-amd64.tar.gz"
    dest: "/home/ubuntu/alertmanager"
    remote_src: yes

- name: move files
  ansible.builtin.copy:
    src: "/home/ubuntu/alertmanager/alertmanager-0.26.0.linux-amd64/"
    dest: "/usr/local/bin/alertmanager/"
    remote_src: yes

- name: create service file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/alertmanager.service"
    content: |
      [Unit]
      Description=Alertmanager
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/alertmanager/alertmanager --config.file=/usr/local/bin/alertmanager/alertmanager.yml
      EnvironmentFile=/usr/local/bin/alertmanager/alertmanager.env

      [Install]
      WantedBy=multi-user.target

- name: create env file
  ansible.builtin.copy:
    dest: "/usr/local/bin/alertmanager/alertmanager.env"
    content: |
      AWS_ACCESS_KEY_ID=ASIA3XEMT[...]
      AWS_SECRET_ACCESS_KEY=DRcUKdp[...]
      AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjE[...]

- name: copy alertmanager config file
  ansible.builtin.copy:
    src: files/alertmanager.yml
    dest: "/usr/local/bin/alertmanager/alertmanager.yml"

- name: service always started
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: true
    daemon_reload: yes
