---
- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: create directory
  ansible.builtin.file:
    path: "{{ download_path }}/alertmanager"
    state: directory

- name: download alertmanager tarball
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "{{ download_path }}/alertmanager/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"

- name: unpack installation files
  ansible.builtin.unarchive:
    src: "{{ download_path }}/alertmanager/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "{{ download_path }}/alertmanager"
    remote_src: yes

- name: move files
  ansible.builtin.copy:
    src: "{{ download_path }}/alertmanager/alertmanager-{{ alertmanager_version }}.linux-amd64/"
    dest: "{{ destination_path }}/alertmanager/"
    remote_src: yes

- name: create service file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/alertmanager.service"
    content: |
      [Unit]
      Description=Alertmanager
      After=network.target

      [Service]
      Type=simple
      ExecStart={{ destination_path }}/alertmanager/alertmanager --config.file={{ destination_path }}/alertmanager/alertmanager.yml
      EnvironmentFile={{ destination_path }}/alertmanager/alertmanager.env

      [Install]
      WantedBy=multi-user.target

- name: create env file
  ansible.builtin.copy:
    dest: "{{ destination_path }}/alertmanager/alertmanager.env"
    content: |
      AWS_ACCESS_KEY_ID=ASIA3XEMT[...]
      AWS_SECRET_ACCESS_KEY=DRcUKdp[...]
      AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjE[...]

- name: copy alertmanager config file
  ansible.builtin.template:
    src: templates/alertmanager.yml
    dest: "{{ destination_path }}/alertmanager/alertmanager.yml"

- name: start alertmanager service
  ansible.builtin.systemd:
    name: alertmanager
    state: started
